[package]
name = "wikibooks_rpn_calc_test_ver_zero_one_one"
version = "0.1.1"
authors = ["ItsMe"]
description = "RPN(Reverse Polish Notation) library"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
